### ISSUE TITLE
プレビュー時のToc移動について

### ISSUE THREAD

**Issue by Shigenori-Sagawa-nm** [basyura/inkdrop-sidetoc#1]
プラグインを便利に使わせていただいてます。

プレビュー時も利用できるととても便利かと思ったのですが。
そのあたりは対応されないのでしょうか？

「プレビュー時は表示しない」というTodoがありましたので気になりました。

**Comment by basyura** [comment]
> プラグインを便利に使わせていただいてます。

ありがとうございます！

> 「プレビュー時は表示しない」というTodoがありましたので気になりました。

出さないほうがいいかなとなんとなく思ってました。

勉強しながらなのでどこまでできるのか分からないのが正直なところですが
調査してみようと思います。

**Comment by basyura** [comment]
1.6.2 でプレビュー対応してみました。
プレビュー表示のまま `Reload` をするとノートを切り替えるまで動作しませんが (ヘッダの抽出タイミングが合わない)、
それ以外は動いてそうです。

**Comment by Shigenori-Sagawa-nm** [comment]
@basyura 早速アップデートして利用させていただきました！過去の書いたドキュメントをプレビューで見る機会が多いので、大変使いやすくなりました。対応ありがとうございます！

**Comment by basyura** [comment]
> プレビュー表示のまま Reload をするとノートを切り替えるまで動作しませんが (ヘッダの抽出タイミングが合わない)、

↑ 最新版でこれは直せました。  

プレビューから編集モードに入ったときのカーソル位置が現在のヘッダの位置になっていて微妙ですが  
難しそうなのでこれはそのうちできたらで・・・。
