### ISSUE TITLE
Enhancement Request: Add option for Word Wrap vs Text Wrap

### ISSUE THREAD

**Issue by glisom** [basyura/inkdrop-sidetoc#17]
<img width="235" alt="CleanShot 2023-05-23 at 21 54 31@2x" src="https://github.com/basyura/inkdrop-sidetoc/assets/945818/49b856ca-6b0a-4ca7-97ae-324de035275c">
Would like to be able to wrap on words vs text.
Lmk if you are open to PR's would love to try and add this.

**Comment by basyura** [comment]
That setting already exists. It's the "wrap overflow text" found in the image.

Preferences > Plugins > sidetoc

![](https://raw.githubusercontent.com/basyura/inkdrop-sidetoc/master/images/setting2.png)

**Comment by glisom** [comment]
Sorry should have specified I would like to add a feature to wrap on full words vs text, the example photo I posted showed Selector being split on two lines. Maybe its just the final word that its splitting since some of the lines are splitting correctly.

**Comment by glisom** [comment]
Also, massive fan of your plugin btw, its awesome!

**Comment by basyura** [comment]
Please refer to this [link](https://docs.inkdrop.app/manual/style-tweaks) and add the following to your styles.less.

```less
.sidetoc-pane {
  li {
    word-break: break-word;
  }
}
```

**Comment by glisom** [comment]
Awesome, thank you!
