### ISSUE TITLE
Add vertical scrolling

### ISSUE THREAD

**Issue by davidmigloz** [basyura/inkdrop-sidetoc#2]
Hi @basyura 

Thanks for the plugin, it is very convenient.

However, I've noticed that if the note has more items than the ones that fit in the screen, the last items are not displayed as scroll is not supported.

It would be nice that the list supports vertical scrolling.

E.g. in a note with 30 sections, I can only see until the 27th:
![image](https://user-images.githubusercontent.com/6546265/83658106-0a1afa00-a5c2-11ea-820d-f8859c4ab941.png)

Thank you!

**Comment by basyura** [comment]
Thank you for the report.

I would like to do my best to fix it, but it seems difficult to control the sidebar scrolling.

**Comment by basyura** [comment]
I fixed at v1.6.0

**Comment by davidmigloz** [comment]
awesome! 
works like a charm 👍 
thank you!

**Comment by basyura** [comment]
thanks!
