### ISSUE TITLE
Commentouts (`# comment-text`) in code blocks are recognized as headers

### ISSUE THREAD

**Issue by yuru7** [basyura/inkdrop-sidetoc#3]
当プラグイン、とても助かっています。ありがとうございます。
上手く事象を伝えられないかもしれないので、日本語での報告をお許しください。

Inkdrop ver: 4.7.0-beta2
sidetoc ver: 1.6.0

コードブロック内での `# ` 始まりの行も見出しとして判定されるようです。
例えばシェルスクリプトではこれが `#` がコメントアウト記号となるため、場合によって多くの行が sidetoc にセクションとして表示されてしまいます。

![image](https://user-images.githubusercontent.com/13458509/84231556-65506d80-ab29-11ea-8814-fb5152966905.png)

おそらく行頭から `# ` が含まれるものがコードブロック内外問わずセクションとして認識されているためと推察いたしますが、本来の見出し部分のみが TOC に含まれるようになると嬉しいです。

**Comment by basyura** [comment]
たしかにそうですね・・・確認しますね。

**Comment by basyura** [comment]
"```" 内の `#` を 1.6.1 で対応してみました。  

が、markdown は  `<pre>` タグとか普通に html タグ使えるんですね (今知りました)。    
今の実装はテキストを単純に判定しているだけなのでタグの入れ子を考え始めると厳しいし、
自分がタグを使うことは無さそうなので保留としたいですね・・・。

**Comment by yuru7** [comment]
ご対応ありがとうございます！
コードブロック記号 「```」 内のものが除外されるようになりました。

検証のために使ったものの、Markdown においてタグを使うケースはあまり多くないでしょうし、既知の事象ということで保留にしておいてもよいかと私も思います。

**Comment by basyura** [comment]
html タグはサポート外として、この issue は閉じます。
