### ISSUE TITLE
Improve plugin description

### ISSUE THREAD

**Issue by craftzdog** [basyura/inkdrop-sidetoc#5]
Hi! Thanks a lot for creating this plugin.
It'd be nice to have a more concrete description so that people can easily find your plugin since a lot of people look like searching for it. Something like:

It adds an outline view on the right side of the editor and preview

Hope that helps

**Comment by basyura** [comment]
> It adds an outline view on the right side of the editor and preview

Thanks! I used that description.
(適切だったのでそのまま使わせてもらいました)
