### ISSUE TITLE
Request: support for underline-ish style

### ISSUE THREAD

**Issue by aviscaerulea** [basyura/inkdrop-sidetoc#7]
Inkdrop supports underline-ish style for H1 and H2 headers.
The official toc plugin also supports underline-ish style, so it would be nice if sidetoc could support it as well.

https://docs.inkdrop.app/manual/markdown-cheatsheet/#headers

**Comment by basyura** [comment]
Thank you for reporting!

Currently, I'm parsing text like this. So simply.

* https://github.com/basyura/inkdrop-sidetoc/blob/master/src/ripper.ts#L35

```js
// count of #
let i = 0;
for (; i < v.length; i++) {
  if (v[i] != "#") {
    break;
  }
}
```

Maybe I can parse underline-ish, but I don't use that.
f more than 3 people need this, I will do it.
