### ISSUE TITLE
Replace input area is hiding

### ISSUE THREAD

**Issue by Kinezi** [basyura/inkdrop-sidetoc#9]
Hi! Thanks for creating the plugin. I'm really enjoying using this!

I've noticed that sometimes I can't see Replace input area.
It'd be helpful that Replace input area shows like plain Inkdrop app does.

#### Reproduce
1. Open a note contains some headers
1. `Alt + Ctrl + F` : Only appers Find input area.
![Clipboard01](https://user-images.githubusercontent.com/18134487/140815716-132ae0b8-473a-4987-8153-e74e5be4c83c.jpg)

1. `Tab` : Replace input area appers with some UI broken.
![Clipboard02](https://user-images.githubusercontent.com/18134487/140815720-7f842e6d-d9c6-4e31-acde-95f4a706aa2f.jpg)

It doesn't happen when I open a note in separate window, or when I open a note contains no header.

#### Info
- Platform: Windows10 21H1
- App Version: 5.4.3
- inkdrop-sidetoc version: 1.12.0

**Comment by basyura** [comment]
hi.

Maybe, I fixed this problem by 1a8eb7b415daa5076fe9c5135ed46ae2e91c1591 .
I will test few days.

thanks!

**Comment by basyura** [comment]
I released.
Could you please check?

**Comment by Kinezi** [comment]
Thanks!
Sure, I'll text you later.

**Comment by Kinezi** [comment]
It's working well in v1.14.0.
Thanks!
